version: '3.2'
services:
  api-server: 
    build: .
    ports:
      - "3001:3001"
      - "3000:3000"
    depends_on:
      - eventstore 
    links:
      - eventstore
    volumes:
      - ./../../..:/go/src 

  eventstore:
     image: tetsuobe/geteventstore
     ports:
      - "1113:1113"
      - "2113:2113"


